# frozen_string_literal: true

begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

require 'rdoc/task'

RDoc::Task.new( :rdoc ) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'ShinySEO'
  rdoc.options << '--line-numbers'
  rdoc.rdoc_files.include( 'README.md' )
  rdoc.rdoc_files.include( 'lib/**/*.rb' )
end

APP_RAKEFILE = File.expand_path( '/Rakefile', __dir__ )

# load 'rails/tasks/engine.rake'
# load 'rails/tasks/statistics.rake'

require 'bundler/gem_tasks'

spec = Gem::Specification.find_by_name 'sitemap_generator'
load "#{spec.gem_dir}/lib/tasks/sitemap_generator_tasks.rake"
