# ShinyCMS ~ https://shinycms.org
#
# Copyright 2009-2020 Denny de la Haye ~ https://denny.me
#
# ShinyCMS is free software; you can redistribute it and/or modify it under the terms of the GPL (version 2 or later)

version: "2"
exclude_patterns:
  db/migrate/*.rb
  db/archived-migrations/*.rb
  plugins/*/db/migrate/*.rb
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  sass-lint:
    enabled: true
  spellcheck:
    enabled: true
  scss-lint:
    enabled: true
  stylelint:
    enabled: true
