# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration

PreCommit:
  CaseConflicts:
    enabled: false

  RuboCop:
    enabled: true
    on_warn: fail

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/*.md'

PrePush:
  RSpec:
    enabled: true
