require: rubocop-rails

# Rubocop does not like lots of Rails' and Activerecord's boilerplate :-\
AllCops:
    Exclude:
        - db/*
        - bin/*

# I have no idea but it was annoying me.
Style/FrozenStringLiteralComment:
    Enabled: false

# Whitespace Considered Helpful
Layout/SpaceInsideArrayLiteralBrackets:
    Enabled: false
Layout/SpaceInsideBlockBraces:
    Enabled: false
Layout/SpaceInsideHashLiteralBraces:
    Enabled: false
Layout/SpaceInsideParens:
    Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
    Enabled: false
Layout/SpaceInsideReferenceBrackets:
    Enabled: false
