branch: 'main'
no_browser: true
paths:
  - app/
  - lib/tasks
  - lib/generators/shiny
  - lib/templates/shiny
  - themes/
  - tools/
  - plugins/ShinyAccess/app/
  - plugins/ShinyBlog/app/
  - plugins/ShinyForms/app/
  - plugins/ShinyInserts/app/
  - plugins/ShinyLists/app/
  - plugins/ShinyNews/app/
  - plugins/ShinyNewsletters/app/
  - plugins/ShinyPages/app/
  - plugins/ShinyProfiles/app/
  - plugins/ShinySearch/app/
