require: rubocop-rails

# Rubocop does not like lots of Rails' and Activerecord's boilerplate :-\
AllCops:
  Exclude:
    - db/**/*
    - bin/*

# Spec files are supposed to be one long block. Shush.
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

# I have no idea what this is but it was annoying me.
Style/FrozenStringLiteralComment:
  Enabled: false

# Allow compact class names (e.g. Admin::Pages::TemplatesController)
Style/ClassAndModuleChildren:
  Enabled: false

# Whitespace Considered Helpful
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false
