# ShinyCMS ~ https://shinycms.org
#
# Copyright 2009-2021 Denny de la Haye ~ https://denny.me
#
# ShinyCMS is free software; you can redistribute it and/or modify it under the terms of the GPL (version 2 or later)

# Created with `rubocop --auto-gen-config` on 2021-02-07 using RuboCop version 1.9.1
#
# Entries in this file should be removed as the offenses are removed from the code base.
#
# This file should be regenerated regularly as the code changes, and whenever Rubocop is updated.

# Offense count: 28
RSpec/AnyInstance:
  Exclude:
    - 'plugins/ShinyForms/spec/requests/forms_spec.rb'
    - 'plugins/ShinyLists/spec/requests/subscriptions_spec.rb'
    - 'plugins/ShinySearch/spec/requests/search_spec.rb'
    - 'spec/requests/admin/comments_controller_spec.rb'
    - 'spec/requests/discussions_spec.rb'
    - 'spec/requests/main_controller_spec.rb'
    - 'spec/requests/users/registrations_controller_spec.rb'

# Offense count: 240
# Configuration parameters: AssignmentOnly.
RSpec/InstanceVariable:
  Exclude:
    - 'plugins/ShinyBlog/spec/requests/admin/blog_spec.rb'
    - 'plugins/ShinyNews/spec/requests/admin/news_spec.rb'
    - 'plugins/ShinyPages/spec/requests/pages_spec.rb'
    - 'spec/mailer_previews/user_mailer_preview_spec.rb'
    - 'spec/mailers/discussion_mailer_spec.rb'
    - 'spec/models/discussion_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/requests/admin/comments_controller_spec.rb'
    - 'spec/requests/admin/discussions_controller_spec.rb'
    - 'spec/requests/discussions_spec.rb'
    - 'spec/requests/site_settings_controller_spec.rb'
    - 'spec/requests/votes_spec.rb'
    - 'spec/support/shared_examples/pagination_example.rb'
    - 'spec/support/shared_examples/shiny_post_example.rb'
