# ShinyCMS ~ https://shinycms.org
#
# Copyright 2009-2021 Denny de la Haye ~ https://denny.me
#
# ShinyCMS is free software; you can redistribute it and/or modify it under the terms of the GPL (version 2 or later)

# Created with `rubocop --auto-gen-config` on 2021-02-07 using RuboCop version 1.9.1
#
# Entries in this file should be removed as the offenses are removed from the code base.
#
# This file should be regenerated regularly as the code changes, and whenever Rubocop is updated.

# Offense count: 28
RSpec/AnyInstance:
  Exclude:
    - 'plugins/ShinyCMS/spec/requests/shinycms/admin/comments_controller_spec.rb'
    - 'plugins/ShinyCMS/spec/requests/shinycms/discussions_spec.rb'
    - 'plugins/ShinyCMS/spec/requests/shinycms/main_controller_spec.rb'
    - 'plugins/ShinyCMS/spec/requests/shinycms/users/registrations_controller_spec.rb'
    - 'plugins/ShinyForms/spec/requests/forms_spec.rb'
    - 'plugins/ShinyLists/spec/requests/subscriptions_spec.rb'
    - 'plugins/ShinySearch/spec/requests/shiny_search/search_controller_spec.rb'

# Offense count: 195
# Configuration parameters: AssignmentOnly.
RSpec/InstanceVariable:
  Exclude:
    - 'plugins/ShinyCMS/spec/mailers/shinycms/discussion_mailer_spec.rb'
    - 'plugins/ShinyCMS/spec/models/shinycms/discussion_spec.rb'
    - 'plugins/ShinyCMS/spec/requests/shinycms/admin/comments_controller_spec.rb'
    - 'plugins/ShinyCMS/spec/requests/shinycms/admin/discussions_controller_spec.rb'
    - 'plugins/ShinyCMS/spec/requests/shinycms/discussions_spec.rb'
    - 'plugins/ShinyCMS/spec/requests/shinycms/site_settings_controller_spec.rb'
    - 'plugins/ShinyCMS/spec/support/shared_examples/shinycms/pagination_example.rb'
    - 'plugins/ShinyCMS/spec/support/shared_examples/shinycms/shiny_post_example.rb'
    - 'plugins/ShinyNews/spec/requests/admin/news_spec.rb'
    - 'plugins/ShinyPages/spec/requests/pages_spec.rb'
