require: rubocop-rails

# Rubocop does not like lots of Rails' and Activerecord's boilerplate :-\
AllCops:
  EnabledByDefault: true
  Exclude:
    - db/**/*
    - bin/*

# Spec files are supposed to be one long block. Shush.
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

# Whitespace Considered Helpful
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false

# Allow compact class names (e.g. Admin::Pages::TemplatesController)
Style/ClassAndModuleChildren:
  Enabled: false

# I have no idea what this is but it was annoying me.
Style/FrozenStringLiteralComment:
  Enabled: false

# ... nah
Bundler/GemComment:
  Enabled: false
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/StringHashKeys:
  Enabled: false
