require: rubocop-rails

# Rails and ActiveRecord autogenerate a lot of code that fails Rubocop
# (I find this mildly confusing/annoying). Also, there's no point in
# having Rubocop look at JavaScript, images, shell scripts, etc.
AllCops:
  EnabledByDefault: true
  Exclude:
    - db/**/*
    - bin/*
    - app/assets/**/*
    - coverage/**/*
    - docs/*
    - log/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - tools/**/*

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

# TODO: see if I can make this method happy at some point
Metrics/AbcSize:
  Exclude:
    - app/helpers/admin_area_helper.rb

# Spec files and the routes file are supposed to be one long block. Shush.
Metrics/BlockLength:
  Exclude:
    - Gemfile
    - spec/**/*.rb
    - config/routes.rb
    - config/environments/*
    - lib/tasks/*.rake

# Also, spec files with I18n strings in them are more readable with slightly
# long lines than they would be with lots of split lines. Again, shush.
Layout/LineLength:
  Exclude:
    - spec/**/*.rb

# This test is for a feature involving a list of IP addresses
Style/IpAddresses:
  Exclude:
    - spec/requests/admin_spec.rb

# Whitespace Considered Helpful
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false

# Allow compact class names (e.g. Admin::Pages::TemplatesController)
Style/ClassAndModuleChildren:
  Enabled: false

# I'd rather use one style of regex everywhere, that is clearer for munging URLs
# as no need to escape '/': %r{/(path)/parts/} rather than /\/(path)\/parts\//
Style/RegexpLiteral:
  Enabled: false

# ... nah
Bundler/GemComment:
  Enabled: false
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/StringHashKeys:
  Enabled: false
