# ShinyCMS ~ https://shinycms.org
#
# Copyright 2009-2021 Denny de la Haye ~ https://denny.me
#
# ShinyCMS is free software; you can redistribute it and/or modify it under the terms of the GPL (version 2 or later)

# Packwerk config for the root package of the application

# Validate the configuration using `bin/packwerk validate`
# Check your code using `packwerk check`

# Turn on dependency checks for this package?
enforce_dependencies: true

# Turn on privacy checks for this package?
enforce_privacy: false
# Enforcing privacy is often not useful for the root package, because it would
# require defining a public interface for something that should only be a thin
# wrapper in the first place. We recommend enabling this for any new packages
# you create to aid with encapsulation.

# The public path for this package (defaults to `app/public/`)
# public_path: app/public/

# Dependencies of this package (note: these require their own `package.yml` file)
# dependencies:
# - plugins/ShinyCMS  # TODO: FIXME: db/seeds*
# Can't do this^, it's a circular dependency; core plugin depends on main app for Ahoy
