# ShinyCMS ~ https://shinycms.org
#
# Copyright 2009-2026 Denny de la Haye ~ https://denny.me
#
# ShinyCMS is free software; you can redistribute it and/or modify it under the terms of the GPL (version 2 or later)

# Packwerk config for the root package, AKA the host application

# To validate config and check package boundaries: `tools/packwerk`

# Turn on dependency checks for this package?
enforce_dependencies: true

# Turn on privacy checks for this package?
enforce_privacy: false
# Enforcing privacy may not be useful in the host application. It should be
# enabled in all ShinyCMS plugins, to help prevent accidental coupling.

# Set the public path for this package
# public_path: app/public/  # default

# Dependencies of this package (these require their own `package.yml` file)
dependencies:
- plugins/ShinyCMS
- plugins/ShinyPages  # Route extensions, used in config/routes.rb
